## Importing Necessary Libraries

In [5]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px

In [6]:
music_df = pd.read_csv("../data/spotify_dataset.csv")
print(f"Dataset shape {music_df.shape}")
music_df.head()
music_df.info()

Dataset shape (114000, 21)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 114000 entries, 0 to 113999
Data columns (total 21 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   Unnamed: 0        114000 non-null  int64
 1   track_id          114000 non-null  object
 2   artists           113999 non-null  object
 3   album_name        113999 non-null  object
 4   track_name        113999 non-null  object
 5   popularity        114000 non-null  int64
 6   duration_ms       114000 non-null  int64
 7   explicit          114000 non-null  bool
 8   danceability      114000 non-null  float64
 9   energy            114000 non-null  float64
 10  key               114000 non-null  int64
 11  loudness          114000 non-null  float64
 12  mode              114000 non-null  int64
 13  speechiness       114000 non-null  float64
 14  acousticness      114000 non-null  float64
 15  instrumentalness  114000 non-null  float64
 16  liveness          114000 non-null  float64
 17  valence           114000 non-null  float64
 18  tempo             114000 non-null  float64
 19  time_signature    114000 non-null  int64
 20  track_genre       114000 non-null  object
dtypes: bool(1), float64(9), int64(6), object(5)
memory usage: 17.5+ MB

**From .info, we can see that there is one value in album_name, track_name and artists that is not missing.**

In [8]:
music_df.describe()

,Unnamed: 0,popularity,duration_ms,danceability,energy,key,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,time_signature
count,114000.000000,114000.000000,1.140000e+05,114000.000000,114000.000000,114000.000000,114000.000000,114000.000000,114000.000000,114000.000000,114000.000000,114000.000000,114000.000000,114000.000000,114000.000000
mean,56999.500000,33.238535,2.280292e+05,0.566800,0.641383,5.309140,-8.258960,0.637553,0.084652,0.314910,0.156050,0.213553,0.474068,122.147837,3.904035
std,32909.109681,22.305078,1.072977e+05,0.173542,0.251529,3.559987,5.029337,0.480709,0.105732,0.332523,0.309555,0.190378,0.259261,29.978197,0.432621
min,0.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,-49.531000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,28499.750000,17.000000,1.740660e+05,0.456000,0.472000,2.000000,-10.013000,0.000000,0.035900,0.016900,0.000000,0.098000,0.260000,99.218750,4.000000
50%,56999.500000,35.000000,2.129060e+05,0.580000,0.685000,5.000000,-7.004000,1.000000,0.048900,0.169000,0.000042,0.132000,0.464000,122.017000,4.000000
75%,85499.250000,50.000000,2.615060e+05,0.695000,0.854000,8.000000,-5.003000,1.000000,0.084500,0.598000,0.049000,0.273000,0.683000,140.071000,4.000000
max,113999.000000,100.000000,5.237295e+06,0.985000,1.000000,11.000000,4.532000,1.000000,0.965000,0.996000,1.000000,1.000000,0.995000,243.372000,5.000000

In [9]:
print(f"Number of genres: {music_df["track_genre"].nunique()}")
print(f"Number of unique songs: {music_df["track_id"].nunique()}")

music_df["track_genre"].value_counts().head()

Number of genres: 114
Number of unique songs: 89741

track_genre
acoustic             1000
punk-rock            1000
progressive-house    1000
power-pop            1000
pop                  1000
Name: count, dtype: int64

## Checking missing values

In [11]:
missing_values = music_df.isnull().sum()

print("Missing values:")
print(missing_values[missing_values > 0])

display(music_df[music_df.isnull().any(axis=1)])


print("Exact duplicate rows:")
print(music_df.duplicated().sum())

df_without_index = music_df.drop(columns=["Unnamed: 0"])

print("Duplicate rows excluding index:")
print(df_without_index.duplicated().sum())

print("Repeated track IDs:")
print(music_df["track_id"].duplicated().sum())


repeated_tracks = music_df[music_df.duplicated(subset="track_id", keep=False)]

display(repeated_tracks[["track_id", "track_name", "artists", "track_genre"]].head(20))


print("Tracks with zero duration:")
print((music_df["duration_ms"] == 0).sum())

print("Tracks with zero tempo:")
print((music_df["tempo"] == 0).sum())

print("Tracks with popularity outside 0–100:")
print((~music_df["popularity"].between(0, 100)).sum())


print("Genre distribution:")
print(music_df["track_genre"].value_counts().describe())


display(music_df[["duration_ms", "tempo", "loudness","energy", "danceability", "valence"]].describe())

Missing values:
artists       1
album_name    1
track_name    1
dtype: int64

,Unnamed: 0,track_id,artists,album_name,track_name,popularity,duration_ms,explicit,danceability,energy,...,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,time_signature,track_genre
65900,65900,1kR4gIb7nGxHPI3D2ifs59,NaN,NaN,NaN,0,0,False,0.501,0.583,...,-9.46,0,0.0605,0.69,0.00396,0.0747,0.734,138.391,4,k-pop

Exact duplicate rows:
0
Duplicate rows excluding index:
450
Repeated track IDs:
24259

,track_id,track_name,artists,track_genre
0,5SuOikwiRyPMVoIQDJUgSV,Comedy,Gen Hoshino,acoustic
1,4qPNDBW1i3p13qLCt0Ki3A,Ghost - Acoustic,Ben Woodward,acoustic
5,01MVOl9KtVTNfFiBU9I7dc,Days I Will Remember,Tyrone Wells,acoustic
6,6Vc5wAMmXdKIAM7WUoEb7N,Say Something,A Great Big World;Christina Aguilera,acoustic
7,1EzrEOXmMH3G43AXT1y7pA,I'm Yours,Jason Mraz,acoustic
9,7k9GuJYLp2AzqokyEdwEw2,Hunger,Ross Copperman,acoustic
12,4ptDJbJl35d7gQfeNteBwp,Solo,Dan Berk,acoustic
13,0X9MxHR1rTkEHDjp95F2OO,Bad Liar,Anna Hamilton,acoustic
16,6xKeQgzfjixSUld14qUezm,ily (i love you baby),Andrew Foy;Renee Foy,acoustic
17,4Yo0igmcoNyat1secaH0OD,At My Worst,Andrew Foy;Renee Foy,acoustic
22,5TvE3pk05pyFIGdSY9j4DJ,Say Something,A Great Big World;Christina Aguilera,acoustic
23,0BUuuEvNa5T4lMaewyiudB,93 Million Miles,Jason Mraz,acoustic
24,3Hn3LfhrQOaKihdCibJsTs,Unlonely,Jason Mraz,acoustic
25,6D33wCKzWtNEgOovgeVJ7r,Bella Luna,Jason Mraz,acoustic
26,5IfCZDRXZrqZSm8AwE44PG,Winter Wonderland,Jason Mraz,acoustic
27,0dzKBptH2P5j5a0MifBMwM,If It Kills Me,Jason Mraz,acoustic
28,5QAMZTM5cmLg3fHX9ZbTZi,Winter Wonderland,Jason Mraz,acoustic
29,2qESE1ZeWly7I3YjyTXmXh,Winter Wonderland,Jason Mraz,acoustic
30,3EQV1ZHtHvq9OnVRYIdbg3,Winter Wonderland,Jason Mraz,acoustic
31,3ax0rfGb7exLtl02LL08U9,Winter Wonderland,Jason Mraz,acoustic

Tracks with zero duration:
1
Tracks with zero tempo:
157
Tracks with popularity outside 0–100:
0
Genre distribution:
count     114.0
mean     1000.0
std         0.0
min      1000.0
25%      1000.0
50%      1000.0
75%      1000.0
max      1000.0
Name: count, dtype: float64

,duration_ms,tempo,loudness,energy,danceability,valence
count,1.140000e+05,114000.000000,114000.000000,114000.000000,114000.000000,114000.000000
mean,2.280292e+05,122.147837,-8.258960,0.641383,0.566800,0.474068
std,1.072977e+05,29.978197,5.029337,0.251529,0.173542,0.259261
min,0.000000e+00,0.000000,-49.531000,0.000000,0.000000,0.000000
25%,1.740660e+05,99.218750,-10.013000,0.472000,0.456000,0.260000
50%,2.129060e+05,122.017000,-7.004000,0.685000,0.580000,0.464000
75%,2.615060e+05,140.071000,-5.003000,0.854000,0.695000,0.683000
max,5.237295e+06,243.372000,4.532000,1.000000,0.985000,0.995000

In [ ]:
clean_df = music_df.copy()

clean_df = clean_df.drop(columns=["Unnamed: 0"])

clean_df = clean_df.dropna( subset=["track_name", "artists", "album_name"])

clean_df = clean_df.drop_duplicates()

clean_df = clean_df.reset_index(drop=True)

print("Original shape:", music_df.shape)
print("Cleaned shape:", clean_df.shape)
print("Remaining missing values:", clean_df.isnull().sum().sum())
print("Remaining duplicates:", clean_df.duplicated().sum())
selected_genres = [
    "pop", "rock", "classical", "hip-hop",
    "jazz", "electronic", "acoustic"
]

genre_df = clean_df[clean_df["track_genre"].isin(selected_genres)]

genre_summary = (
    genre_df.groupby("track_genre")[
        ["danceability", "energy"]
    ].mean().reset_index()
)

display(genre_summary)

fig = px.scatter(
    genre_summary,
    x="danceability",
    y="energy",
    color="track_genre",
    text="track_genre",
    title="Average Danceability vs. Energy Across Spotify Genres",
    labels={
        "danceability": "Average Danceability",
        "energy": "Average Energy",
        "track_genre": "Genre"
    }
)
fig

Original shape: (114000, 21)
Cleaned shape: (113549, 20)
Remaining missing values: 0
Remaining duplicates: 0

  track_genre  danceability    energy
0    acoustic      0.549593  0.435368
1   classical      0.381959  0.195193
2  electronic      0.652945  0.694752
3     hip-hop      0.735937  0.682361
4        jazz      0.509892  0.353205
5         pop      0.630408  0.605502
6        rock      0.543609  0.679071

In [ ]:
selected_genres = [
    "pop", "rock", "classical", "hip-hop",
    "jazz", "electronic", "acoustic"
]

genre_df = clean_df[clean_df["track_genre"].isin(selected_genres)]

fig = px.box(
    genre_df,
    x="track_genre",
    y="danceability",
    color="track_genre",
    title="Distribution of Danceability Within Spotify Genres",
    labels={
        "track_genre": "Genre",
        "danceability": "Danceability"
    },
    points=False
)

fig.update_layout(showlegend=False)

fig.show()

genre_variation = (
    genre_df.groupby("track_genre")["danceability"]
    .agg(["count", "mean", "median", "std", "min", "max"])
    .round(3)
)

display(genre_variation)